name: filtering with events

on: 
  push:
    branches:
      - main
      - '!feature/*'
  pull_request:
    types:
      - opened
      - closed
    paths-ignore:
      - README.md
    branches:
      - main


jobs: 
  hello:
    runs-on: ubuntu-latest
    steps:
    - run: echo this workflow is executed for event type - ${{ github.event_name }}
    