name: matrix(additional config) workflow

on: push

jobs: 
  deploy:
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, windows-latest]
        images: [hello-world, alpine]
        exclude: 
          - images: alpine
            os: windows-latest
        include: 
          - images: amd64/alpine
            os: ubuntu-20.04 
    runs-on: ${{ matrix.os }}
    steps:
      - name: Echo Docker Details
        run: docker info
      
      - name: Running image on ${{ matrix.os }}
        run: docker pull ${{ matrix.images }}
    