name: example workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout the repo
              uses: actions/checkout@v4

            - name: welcome message
              run: echo "welcome"

            - name: list files
              run: ls
            
            - name: read
              run: cat README.md

