name: concurrency workflow

on: push

jobs:
    build:
      runs-on: ubuntu-latest
      steps: 
        - name: print stage name
          run: echo deploy stage
    
    deploy:
      concurrency:
        group: production-deploy
        cancel-in-progress: false
      runs-on: ubuntu-latest
      steps:
        - name: sleep for 100 seconds
          run: sleep 100
      
   